language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-srfrnk-webapp' ]; then cd .. && eval "mv $currentfolder generator-srfrnk-webapp" && cd generator-srfrnk-webapp; fi

